spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Microservices_db
  application:
    name: RATING-SERVICE

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-url: http://localhost:8761/eureka
